import type { ElementTrackingNode } from './tree';
import type { MathCommand } from './commands/mathCommand';
import type { TextBlock } from './commands/text';
import type { NodeBase } from './nodeBase';

export function linkElementByBlockNode(elm: Element, blockNode: NodeBase) {
  (elm as ElementTrackingNode).mqBlockNode = blockNode;
}

export function linkElementByCmdNode(elm: Element, cmdNode: MathCommand | TextBlock) {
  (elm as ElementTrackingNode).mqCmdNode = cmdNode;
}

// The mqBlockNode and mqCmdNode custom properties link back from the
// DOM nodes generated by MathQuill to the MQNodes that generated
// them. This is useful for looking up MQNodes in event handlers and
// in the mq(elt) public API method
export function getNodeOfElement(el: Element | undefined) {
  if (!el) return;
  if (!el.nodeType)
    throw new Error('must pass an Element to getNodeOfElement');

  var elTrackingNode = el as ElementTrackingNode;
  return elTrackingNode.mqBlockNode || elTrackingNode.mqCmdNode;
}